<?php

namespace Guillaumetissier\QrCode\Tests\BitMatrixBuilder\FunctionPatterns\Placer\Positions;

use Guillaumetissier\QrCode\BitMatrixBuilder\FunctionPatterns\Placer\Positions\AlignmentPatternCenterPositions;
use Guillaumetissier\QrCode\Common\Position;
use Guillaumetissier\QrCode\Enums\Version;
use Guillaumetissier\QrCode\Exception\MissingInfoException;
use PHPUnit\Framework\TestCase;

final class AlignmentPatternCenterPositionsTest extends TestCase
{
    private AlignmentPatternCenterPositions $positions;

    protected function setUp(): void
    {
        parent::setUp();

        $this->positions = new AlignmentPatternCenterPositions();
    }

    /**
     * @param Version $version
     * @param array<Position> $expectedPositions
     * @return void
     * @throws MissingInfoException
     * @dataProvider dataPositions
     */
    public function testGetPositions(Version $version, array $expectedPositions): void
    {
        $p = 0;
        foreach ($this->positions->withVersion($version)->positions() as $position) {
            $this->assertEquals($expectedPositions[$p++], $position);
        }
    }

    public static function dataPositions(): \Generator
    {
        yield [Version::V02, [Position::fromTopLeft(18, 18)]];
        yield [Version::V03, [Position::fromTopLeft(22, 22)]];
        yield [Version::V04, [Position::fromTopLeft(26, 26)]];
        yield [Version::V05, [Position::fromTopLeft(30, 30)]];
        yield [Version::V06, [Position::fromTopLeft(34, 34)]];
        yield [
            Version::V07,
            [
                Position::fromTopLeft(6, 22),
                Position::fromTopLeft(22, 6),
                Position::fromTopLeft(22, 22),
                Position::fromTopLeft(22, 38),
                Position::fromTopLeft(38, 22),
                Position::fromTopLeft(38, 38),
            ],
        ];
        yield [
            Version::V08,
            [
                Position::fromTopLeft(6, 24),
                Position::fromTopLeft(24, 6),
                Position::fromTopLeft(24, 24),
                Position::fromTopLeft(24, 42),
                Position::fromTopLeft(42, 24),
                Position::fromTopLeft(42, 42),
            ],
        ];
        yield [
            Version::V09,
            [
                Position::fromTopLeft(6, 26),
                Position::fromTopLeft(26, 6),
                Position::fromTopLeft(26, 26),
                Position::fromTopLeft(26, 46),
                Position::fromTopLeft(46, 26),
                Position::fromTopLeft(46, 46),
            ],
        ];
        yield [
            Version::V10,
            [
                Position::fromTopLeft(6, 28),
                Position::fromTopLeft(28, 6),
                Position::fromTopLeft(28, 28),
                Position::fromTopLeft(28, 50),
                Position::fromTopLeft(50, 28),
                Position::fromTopLeft(50, 50),
            ],
        ];
        yield [
            Version::V11,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 54),
                Position::fromTopLeft(54, 30),
                Position::fromTopLeft(54, 54),
            ],
        ];
        yield [
            Version::V12,
            [
                Position::fromTopLeft(6, 32),
                Position::fromTopLeft(32, 6),
                Position::fromTopLeft(32, 32),
                Position::fromTopLeft(32, 58),
                Position::fromTopLeft(58, 32),
                Position::fromTopLeft(58, 58),
            ],
        ];
        yield [
            Version::V13,
            [
                Position::fromTopLeft(6, 34),
                Position::fromTopLeft(34, 6),
                Position::fromTopLeft(34, 34),
                Position::fromTopLeft(34, 62),
                Position::fromTopLeft(62, 34),
                Position::fromTopLeft(62, 62),
            ],
        ];
        yield [
            Version::V14,
            [
                Position::fromTopLeft(6, 26),
                Position::fromTopLeft(6, 46),
                Position::fromTopLeft(26, 6),
                Position::fromTopLeft(26, 26),
                Position::fromTopLeft(26, 46),
                Position::fromTopLeft(26, 66),
                Position::fromTopLeft(46, 6),
                Position::fromTopLeft(46, 26),
                Position::fromTopLeft(46, 46),
                Position::fromTopLeft(46, 66),
                Position::fromTopLeft(66, 26),
                Position::fromTopLeft(66, 46),
                Position::fromTopLeft(66, 66),
            ],
        ];
        yield [
            Version::V15,
            [
                Position::fromTopLeft(6, 26),
                Position::fromTopLeft(6, 48),
                Position::fromTopLeft(26, 6),
                Position::fromTopLeft(26, 26),
                Position::fromTopLeft(26, 48),
                Position::fromTopLeft(26, 70),
                Position::fromTopLeft(48, 6),
                Position::fromTopLeft(48, 26),
                Position::fromTopLeft(48, 48),
                Position::fromTopLeft(48, 70),
                Position::fromTopLeft(70, 26),
                Position::fromTopLeft(70, 48),
                Position::fromTopLeft(70, 70),
            ],
        ];
        yield [
            Version::V16,
            [
                Position::fromTopLeft(6, 26),
                Position::fromTopLeft(6, 50),
                Position::fromTopLeft(26, 6),
                Position::fromTopLeft(26, 26),
                Position::fromTopLeft(26, 50),
                Position::fromTopLeft(26, 74),
                Position::fromTopLeft(50, 6),
                Position::fromTopLeft(50, 26),
                Position::fromTopLeft(50, 50),
                Position::fromTopLeft(50, 74),
                Position::fromTopLeft(74, 26),
                Position::fromTopLeft(74, 50),
                Position::fromTopLeft(74, 74),
            ],
        ];
        yield [
            Version::V17,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 54),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 54),
                Position::fromTopLeft(30, 78),
                Position::fromTopLeft(54, 6),
                Position::fromTopLeft(54, 30),
                Position::fromTopLeft(54, 54),
                Position::fromTopLeft(54, 78),
                Position::fromTopLeft(78, 30),
                Position::fromTopLeft(78, 54),
                Position::fromTopLeft(78, 78),
            ],
        ];
        yield [
            Version::V18,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 56),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 56),
                Position::fromTopLeft(30, 82),
                Position::fromTopLeft(56, 6),
                Position::fromTopLeft(56, 30),
                Position::fromTopLeft(56, 56),
                Position::fromTopLeft(56, 82),
                Position::fromTopLeft(82, 30),
                Position::fromTopLeft(82, 56),
                Position::fromTopLeft(82, 82),
            ],
        ];
        yield [
            Version::V19,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 58),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 58),
                Position::fromTopLeft(30, 86),
                Position::fromTopLeft(58, 6),
                Position::fromTopLeft(58, 30),
                Position::fromTopLeft(58, 58),
                Position::fromTopLeft(58, 86),
                Position::fromTopLeft(86, 30),
                Position::fromTopLeft(86, 58),
                Position::fromTopLeft(86, 86),
            ],
        ];
        yield [
            Version::V20,
            [
                Position::fromTopLeft(6, 34),
                Position::fromTopLeft(6, 62),
                Position::fromTopLeft(34, 6),
                Position::fromTopLeft(34, 34),
                Position::fromTopLeft(34, 62),
                Position::fromTopLeft(34, 90),
                Position::fromTopLeft(62, 6),
                Position::fromTopLeft(62, 34),
                Position::fromTopLeft(62, 62),
                Position::fromTopLeft(62, 90),
                Position::fromTopLeft(90, 34),
                Position::fromTopLeft(90, 62),
                Position::fromTopLeft(90, 90),
            ],
        ];
        yield [
            Version::V21,
            [
                Position::fromTopLeft(6, 28),
                Position::fromTopLeft(6, 50),
                Position::fromTopLeft(6, 72),
                Position::fromTopLeft(28, 6),
                Position::fromTopLeft(28, 28),
                Position::fromTopLeft(28, 50),
                Position::fromTopLeft(28, 72),
                Position::fromTopLeft(28, 94),
                Position::fromTopLeft(50, 6),
                Position::fromTopLeft(50, 28),
                Position::fromTopLeft(50, 50),
                Position::fromTopLeft(50, 72),
                Position::fromTopLeft(50, 94),
                Position::fromTopLeft(72, 6),
                Position::fromTopLeft(72, 28),
                Position::fromTopLeft(72, 50),
                Position::fromTopLeft(72, 72),
                Position::fromTopLeft(72, 94),
                Position::fromTopLeft(94, 28),
                Position::fromTopLeft(94, 50),
                Position::fromTopLeft(94, 72),
                Position::fromTopLeft(94, 94),
            ],
        ];
        yield [
            Version::V22,
            [
                Position::fromTopLeft(6, 26),
                Position::fromTopLeft(6, 50),
                Position::fromTopLeft(6, 74),
                Position::fromTopLeft(26, 6),
                Position::fromTopLeft(26, 26),
                Position::fromTopLeft(26, 50),
                Position::fromTopLeft(26, 74),
                Position::fromTopLeft(26, 98),
                Position::fromTopLeft(50, 6),
                Position::fromTopLeft(50, 26),
                Position::fromTopLeft(50, 50),
                Position::fromTopLeft(50, 74),
                Position::fromTopLeft(50, 98),
                Position::fromTopLeft(74, 6),
                Position::fromTopLeft(74, 26),
                Position::fromTopLeft(74, 50),
                Position::fromTopLeft(74, 74),
                Position::fromTopLeft(74, 98),
                Position::fromTopLeft(98, 26),
                Position::fromTopLeft(98, 50),
                Position::fromTopLeft(98, 74),
                Position::fromTopLeft(98, 98),
            ],
        ];
        yield [
            Version::V23,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 54),
                Position::fromTopLeft(6, 78),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 54),
                Position::fromTopLeft(30, 78),
                Position::fromTopLeft(30, 102),
                Position::fromTopLeft(54, 6),
                Position::fromTopLeft(54, 30),
                Position::fromTopLeft(54, 54),
                Position::fromTopLeft(54, 78),
                Position::fromTopLeft(54, 102),
                Position::fromTopLeft(78, 6),
                Position::fromTopLeft(78, 30),
                Position::fromTopLeft(78, 54),
                Position::fromTopLeft(78, 78),
                Position::fromTopLeft(78, 102),
                Position::fromTopLeft(102, 30),
                Position::fromTopLeft(102, 54),
                Position::fromTopLeft(102, 78),
                Position::fromTopLeft(102, 102),
            ],
        ];
        yield [
            Version::V24,
            [
                Position::fromTopLeft(6, 28),
                Position::fromTopLeft(6, 54),
                Position::fromTopLeft(6, 80),
                Position::fromTopLeft(28, 6),
                Position::fromTopLeft(28, 28),
                Position::fromTopLeft(28, 54),
                Position::fromTopLeft(28, 80),
                Position::fromTopLeft(28, 106),
                Position::fromTopLeft(54, 6),
                Position::fromTopLeft(54, 28),
                Position::fromTopLeft(54, 54),
                Position::fromTopLeft(54, 80),
                Position::fromTopLeft(54, 106),
                Position::fromTopLeft(80, 6),
                Position::fromTopLeft(80, 28),
                Position::fromTopLeft(80, 54),
                Position::fromTopLeft(80, 80),
                Position::fromTopLeft(80, 106),
                Position::fromTopLeft(106, 28),
                Position::fromTopLeft(106, 54),
                Position::fromTopLeft(106, 80),
                Position::fromTopLeft(106, 106),
            ],
        ];
        yield [
            Version::V25,
            [
                Position::fromTopLeft(6, 32),
                Position::fromTopLeft(6, 58),
                Position::fromTopLeft(6, 84),
                Position::fromTopLeft(32, 6),
                Position::fromTopLeft(32, 32),
                Position::fromTopLeft(32, 58),
                Position::fromTopLeft(32, 84),
                Position::fromTopLeft(32, 110),
                Position::fromTopLeft(58, 6),
                Position::fromTopLeft(58, 32),
                Position::fromTopLeft(58, 58),
                Position::fromTopLeft(58, 84),
                Position::fromTopLeft(58, 110),
                Position::fromTopLeft(84, 6),
                Position::fromTopLeft(84, 32),
                Position::fromTopLeft(84, 58),
                Position::fromTopLeft(84, 84),
                Position::fromTopLeft(84, 110),
                Position::fromTopLeft(110, 32),
                Position::fromTopLeft(110, 58),
                Position::fromTopLeft(110, 84),
                Position::fromTopLeft(110, 110),
            ],
        ];
        yield [
            Version::V26,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 58),
                Position::fromTopLeft(6, 86),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 58),
                Position::fromTopLeft(30, 86),
                Position::fromTopLeft(30, 114),
                Position::fromTopLeft(58, 6),
                Position::fromTopLeft(58, 30),
                Position::fromTopLeft(58, 58),
                Position::fromTopLeft(58, 86),
                Position::fromTopLeft(58, 114),
                Position::fromTopLeft(86, 6),
                Position::fromTopLeft(86, 30),
                Position::fromTopLeft(86, 58),
                Position::fromTopLeft(86, 86),
                Position::fromTopLeft(86, 114),
                Position::fromTopLeft(114, 30),
                Position::fromTopLeft(114, 58),
                Position::fromTopLeft(114, 86),
                Position::fromTopLeft(114, 114),
            ],
        ];
        yield [
            Version::V27,
            [
                Position::fromTopLeft(6, 34),
                Position::fromTopLeft(6, 62),
                Position::fromTopLeft(6, 90),
                Position::fromTopLeft(34, 6),
                Position::fromTopLeft(34, 34),
                Position::fromTopLeft(34, 62),
                Position::fromTopLeft(34, 90),
                Position::fromTopLeft(34, 118),
                Position::fromTopLeft(62, 6),
                Position::fromTopLeft(62, 34),
                Position::fromTopLeft(62, 62),
                Position::fromTopLeft(62, 90),
                Position::fromTopLeft(62, 118),
                Position::fromTopLeft(90, 6),
                Position::fromTopLeft(90, 34),
                Position::fromTopLeft(90, 62),
                Position::fromTopLeft(90, 90),
                Position::fromTopLeft(90, 118),
                Position::fromTopLeft(118, 34),
                Position::fromTopLeft(118, 62),
                Position::fromTopLeft(118, 90),
                Position::fromTopLeft(118, 118),
            ],
        ];
        yield [
            Version::V28,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 50),
                Position::fromTopLeft(6, 74),
                Position::fromTopLeft(6, 98),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 50),
                Position::fromTopLeft(30, 74),
                Position::fromTopLeft(30, 98),
                Position::fromTopLeft(30, 122),
                Position::fromTopLeft(50, 6),
                Position::fromTopLeft(50, 30),
                Position::fromTopLeft(50, 50),
                Position::fromTopLeft(50, 74),
                Position::fromTopLeft(50, 98),
                Position::fromTopLeft(50, 122),
                Position::fromTopLeft(74, 6),
                Position::fromTopLeft(74, 30),
                Position::fromTopLeft(74, 50),
                Position::fromTopLeft(74, 74),
                Position::fromTopLeft(74, 98),
                Position::fromTopLeft(74, 122),
                Position::fromTopLeft(98, 6),
                Position::fromTopLeft(98, 30),
                Position::fromTopLeft(98, 50),
                Position::fromTopLeft(98, 74),
                Position::fromTopLeft(98, 98),
                Position::fromTopLeft(98, 122),
                Position::fromTopLeft(122, 30),
                Position::fromTopLeft(122, 50),
                Position::fromTopLeft(122, 74),
                Position::fromTopLeft(122, 98),
                Position::fromTopLeft(122, 122),
            ],
        ];
        yield [
            Version::V29,
            [
                Position::fromTopLeft(6, 34),
                Position::fromTopLeft(6, 54),
                Position::fromTopLeft(6, 78),
                Position::fromTopLeft(6, 102),
                Position::fromTopLeft(34, 6),
                Position::fromTopLeft(34, 34),
                Position::fromTopLeft(34, 54),
                Position::fromTopLeft(34, 78),
                Position::fromTopLeft(34, 102),
                Position::fromTopLeft(34, 126),
                Position::fromTopLeft(54, 6),
                Position::fromTopLeft(54, 34),
                Position::fromTopLeft(54, 54),
                Position::fromTopLeft(54, 78),
                Position::fromTopLeft(54, 102),
                Position::fromTopLeft(54, 126),
                Position::fromTopLeft(78, 6),
                Position::fromTopLeft(78, 34),
                Position::fromTopLeft(78, 54),
                Position::fromTopLeft(78, 78),
                Position::fromTopLeft(78, 102),
                Position::fromTopLeft(78, 126),
                Position::fromTopLeft(102, 6),
                Position::fromTopLeft(102, 34),
                Position::fromTopLeft(102, 54),
                Position::fromTopLeft(102, 78),
                Position::fromTopLeft(102, 102),
                Position::fromTopLeft(102, 126),
                Position::fromTopLeft(126, 34),
                Position::fromTopLeft(126, 54),
                Position::fromTopLeft(126, 78),
                Position::fromTopLeft(126, 102),
                Position::fromTopLeft(126, 126),
            ],
        ];
        yield [
            Version::V30,
            [
                Position::fromTopLeft(6, 26),
                Position::fromTopLeft(6, 52),
                Position::fromTopLeft(6, 78),
                Position::fromTopLeft(6, 104),
                Position::fromTopLeft(26, 6),
                Position::fromTopLeft(26, 26),
                Position::fromTopLeft(26, 52),
                Position::fromTopLeft(26, 78),
                Position::fromTopLeft(26, 104),
                Position::fromTopLeft(26, 130),
                Position::fromTopLeft(52, 6),
                Position::fromTopLeft(52, 26),
                Position::fromTopLeft(52, 52),
                Position::fromTopLeft(52, 78),
                Position::fromTopLeft(52, 104),
                Position::fromTopLeft(52, 130),
                Position::fromTopLeft(78, 6),
                Position::fromTopLeft(78, 26),
                Position::fromTopLeft(78, 52),
                Position::fromTopLeft(78, 78),
                Position::fromTopLeft(78, 104),
                Position::fromTopLeft(78, 130),
                Position::fromTopLeft(104, 6),
                Position::fromTopLeft(104, 26),
                Position::fromTopLeft(104, 52),
                Position::fromTopLeft(104, 78),
                Position::fromTopLeft(104, 104),
                Position::fromTopLeft(104, 130),
                Position::fromTopLeft(130, 26),
                Position::fromTopLeft(130, 52),
                Position::fromTopLeft(130, 78),
                Position::fromTopLeft(130, 104),
                Position::fromTopLeft(130, 130),
            ],
        ];
        yield [
            Version::V31,
            [
                Position::fromTopLeft(6, 34),
                Position::fromTopLeft(6, 56),
                Position::fromTopLeft(6, 82),
                Position::fromTopLeft(6, 108),
                Position::fromTopLeft(34, 6),
                Position::fromTopLeft(34, 34),
                Position::fromTopLeft(34, 56),
                Position::fromTopLeft(34, 82),
                Position::fromTopLeft(34, 108),
                Position::fromTopLeft(34, 134),
                Position::fromTopLeft(56, 6),
                Position::fromTopLeft(56, 34),
                Position::fromTopLeft(56, 56),
                Position::fromTopLeft(56, 82),
                Position::fromTopLeft(56, 108),
                Position::fromTopLeft(56, 134),
                Position::fromTopLeft(82, 6),
                Position::fromTopLeft(82, 34),
                Position::fromTopLeft(82, 56),
                Position::fromTopLeft(82, 82),
                Position::fromTopLeft(82, 108),
                Position::fromTopLeft(82, 134),
                Position::fromTopLeft(108, 6),
                Position::fromTopLeft(108, 34),
                Position::fromTopLeft(108, 56),
                Position::fromTopLeft(108, 82),
                Position::fromTopLeft(108, 108),
                Position::fromTopLeft(108, 134),
                Position::fromTopLeft(134, 34),
                Position::fromTopLeft(134, 56),
                Position::fromTopLeft(134, 82),
                Position::fromTopLeft(134, 108),
                Position::fromTopLeft(134, 134),
            ],
        ];
        yield [
            Version::V32,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 60),
                Position::fromTopLeft(6, 86),
                Position::fromTopLeft(6, 112),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 60),
                Position::fromTopLeft(30, 86),
                Position::fromTopLeft(30, 112),
                Position::fromTopLeft(30, 138),
                Position::fromTopLeft(60, 6),
                Position::fromTopLeft(60, 30),
                Position::fromTopLeft(60, 60),
                Position::fromTopLeft(60, 86),
                Position::fromTopLeft(60, 112),
                Position::fromTopLeft(60, 138),
                Position::fromTopLeft(86, 6),
                Position::fromTopLeft(86, 30),
                Position::fromTopLeft(86, 60),
                Position::fromTopLeft(86, 86),
                Position::fromTopLeft(86, 112),
                Position::fromTopLeft(86, 138),
                Position::fromTopLeft(112, 6),
                Position::fromTopLeft(112, 30),
                Position::fromTopLeft(112, 60),
                Position::fromTopLeft(112, 86),
                Position::fromTopLeft(112, 112),
                Position::fromTopLeft(112, 138),
                Position::fromTopLeft(138, 30),
                Position::fromTopLeft(138, 60),
                Position::fromTopLeft(138, 86),
                Position::fromTopLeft(138, 112),
                Position::fromTopLeft(138, 138),
            ],
        ];
        yield [
            Version::V33,
            [
                Position::fromTopLeft(6, 34),
                Position::fromTopLeft(6, 58),
                Position::fromTopLeft(6, 86),
                Position::fromTopLeft(6, 114),
                Position::fromTopLeft(34, 6),
                Position::fromTopLeft(34, 34),
                Position::fromTopLeft(34, 58),
                Position::fromTopLeft(34, 86),
                Position::fromTopLeft(34, 114),
                Position::fromTopLeft(34, 142),
                Position::fromTopLeft(58, 6),
                Position::fromTopLeft(58, 34),
                Position::fromTopLeft(58, 58),
                Position::fromTopLeft(58, 86),
                Position::fromTopLeft(58, 114),
                Position::fromTopLeft(58, 142),
                Position::fromTopLeft(86, 6),
                Position::fromTopLeft(86, 34),
                Position::fromTopLeft(86, 58),
                Position::fromTopLeft(86, 86),
                Position::fromTopLeft(86, 114),
                Position::fromTopLeft(86, 142),
                Position::fromTopLeft(114, 6),
                Position::fromTopLeft(114, 34),
                Position::fromTopLeft(114, 58),
                Position::fromTopLeft(114, 86),
                Position::fromTopLeft(114, 114),
                Position::fromTopLeft(114, 142),
                Position::fromTopLeft(142, 34),
                Position::fromTopLeft(142, 58),
                Position::fromTopLeft(142, 86),
                Position::fromTopLeft(142, 114),
                Position::fromTopLeft(142, 142),
            ],
        ];
        yield [
            Version::V34,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 62),
                Position::fromTopLeft(6, 90),
                Position::fromTopLeft(6, 118),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 62),
                Position::fromTopLeft(30, 90),
                Position::fromTopLeft(30, 118),
                Position::fromTopLeft(30, 146),
                Position::fromTopLeft(62, 6),
                Position::fromTopLeft(62, 30),
                Position::fromTopLeft(62, 62),
                Position::fromTopLeft(62, 90),
                Position::fromTopLeft(62, 118),
                Position::fromTopLeft(62, 146),
                Position::fromTopLeft(90, 6),
                Position::fromTopLeft(90, 30),
                Position::fromTopLeft(90, 62),
                Position::fromTopLeft(90, 90),
                Position::fromTopLeft(90, 118),
                Position::fromTopLeft(90, 146),
                Position::fromTopLeft(118, 6),
                Position::fromTopLeft(118, 30),
                Position::fromTopLeft(118, 62),
                Position::fromTopLeft(118, 90),
                Position::fromTopLeft(118, 118),
                Position::fromTopLeft(118, 146),
                Position::fromTopLeft(146, 30),
                Position::fromTopLeft(146, 62),
                Position::fromTopLeft(146, 90),
                Position::fromTopLeft(146, 118),
                Position::fromTopLeft(146, 146),
            ],
        ];
        yield [
            Version::V35,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 54),
                Position::fromTopLeft(6, 78),
                Position::fromTopLeft(6, 102),
                Position::fromTopLeft(6, 126),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 54),
                Position::fromTopLeft(30, 78),
                Position::fromTopLeft(30, 102),
                Position::fromTopLeft(30, 126),
                Position::fromTopLeft(30, 150),
                Position::fromTopLeft(54, 6),
                Position::fromTopLeft(54, 30),
                Position::fromTopLeft(54, 54),
                Position::fromTopLeft(54, 78),
                Position::fromTopLeft(54, 102),
                Position::fromTopLeft(54, 126),
                Position::fromTopLeft(54, 150),
                Position::fromTopLeft(78, 6),
                Position::fromTopLeft(78, 30),
                Position::fromTopLeft(78, 54),
                Position::fromTopLeft(78, 78),
                Position::fromTopLeft(78, 102),
                Position::fromTopLeft(78, 126),
                Position::fromTopLeft(78, 150),
                Position::fromTopLeft(102, 6),
                Position::fromTopLeft(102, 30),
                Position::fromTopLeft(102, 54),
                Position::fromTopLeft(102, 78),
                Position::fromTopLeft(102, 102),
                Position::fromTopLeft(102, 126),
                Position::fromTopLeft(102, 150),
                Position::fromTopLeft(126, 6),
                Position::fromTopLeft(126, 30),
                Position::fromTopLeft(126, 54),
                Position::fromTopLeft(126, 78),
                Position::fromTopLeft(126, 102),
                Position::fromTopLeft(126, 126),
                Position::fromTopLeft(126, 150),
                Position::fromTopLeft(150, 30),
                Position::fromTopLeft(150, 54),
                Position::fromTopLeft(150, 78),
                Position::fromTopLeft(150, 102),
                Position::fromTopLeft(150, 126),
                Position::fromTopLeft(150, 150),
            ],
        ];
        yield [
            Version::V36,
            [
                Position::fromTopLeft(6, 24),
                Position::fromTopLeft(6, 50),
                Position::fromTopLeft(6, 76),
                Position::fromTopLeft(6, 102),
                Position::fromTopLeft(6, 128),
                Position::fromTopLeft(24, 6),
                Position::fromTopLeft(24, 24),
                Position::fromTopLeft(24, 50),
                Position::fromTopLeft(24, 76),
                Position::fromTopLeft(24, 102),
                Position::fromTopLeft(24, 128),
                Position::fromTopLeft(24, 154),
                Position::fromTopLeft(50, 6),
                Position::fromTopLeft(50, 24),
                Position::fromTopLeft(50, 50),
                Position::fromTopLeft(50, 76),
                Position::fromTopLeft(50, 102),
                Position::fromTopLeft(50, 128),
                Position::fromTopLeft(50, 154),
                Position::fromTopLeft(76, 6),
                Position::fromTopLeft(76, 24),
                Position::fromTopLeft(76, 50),
                Position::fromTopLeft(76, 76),
                Position::fromTopLeft(76, 102),
                Position::fromTopLeft(76, 128),
                Position::fromTopLeft(76, 154),
                Position::fromTopLeft(102, 6),
                Position::fromTopLeft(102, 24),
                Position::fromTopLeft(102, 50),
                Position::fromTopLeft(102, 76),
                Position::fromTopLeft(102, 102),
                Position::fromTopLeft(102, 128),
                Position::fromTopLeft(102, 154),
                Position::fromTopLeft(128, 6),
                Position::fromTopLeft(128, 24),
                Position::fromTopLeft(128, 50),
                Position::fromTopLeft(128, 76),
                Position::fromTopLeft(128, 102),
                Position::fromTopLeft(128, 128),
                Position::fromTopLeft(128, 154),
                Position::fromTopLeft(154, 24),
                Position::fromTopLeft(154, 50),
                Position::fromTopLeft(154, 76),
                Position::fromTopLeft(154, 102),
                Position::fromTopLeft(154, 128),
                Position::fromTopLeft(154, 154),
            ],
        ];
        yield [
            Version::V37,
            [
                Position::fromTopLeft(6, 28),
                Position::fromTopLeft(6, 54),
                Position::fromTopLeft(6, 80),
                Position::fromTopLeft(6, 106),
                Position::fromTopLeft(6, 132),
                Position::fromTopLeft(28, 6),
                Position::fromTopLeft(28, 28),
                Position::fromTopLeft(28, 54),
                Position::fromTopLeft(28, 80),
                Position::fromTopLeft(28, 106),
                Position::fromTopLeft(28, 132),
                Position::fromTopLeft(28, 158),
                Position::fromTopLeft(54, 6),
                Position::fromTopLeft(54, 28),
                Position::fromTopLeft(54, 54),
                Position::fromTopLeft(54, 80),
                Position::fromTopLeft(54, 106),
                Position::fromTopLeft(54, 132),
                Position::fromTopLeft(54, 158),
                Position::fromTopLeft(80, 6),
                Position::fromTopLeft(80, 28),
                Position::fromTopLeft(80, 54),
                Position::fromTopLeft(80, 80),
                Position::fromTopLeft(80, 106),
                Position::fromTopLeft(80, 132),
                Position::fromTopLeft(80, 158),
                Position::fromTopLeft(106, 6),
                Position::fromTopLeft(106, 28),
                Position::fromTopLeft(106, 54),
                Position::fromTopLeft(106, 80),
                Position::fromTopLeft(106, 106),
                Position::fromTopLeft(106, 132),
                Position::fromTopLeft(106, 158),
                Position::fromTopLeft(132, 6),
                Position::fromTopLeft(132, 28),
                Position::fromTopLeft(132, 54),
                Position::fromTopLeft(132, 80),
                Position::fromTopLeft(132, 106),
                Position::fromTopLeft(132, 132),
                Position::fromTopLeft(132, 158),
                Position::fromTopLeft(158, 28),
                Position::fromTopLeft(158, 54),
                Position::fromTopLeft(158, 80),
                Position::fromTopLeft(158, 106),
                Position::fromTopLeft(158, 132),
                Position::fromTopLeft(158, 158),
            ],
        ];
        yield [
            Version::V38,
            [
                Position::fromTopLeft(6, 32),
                Position::fromTopLeft(6, 58),
                Position::fromTopLeft(6, 84),
                Position::fromTopLeft(6, 110),
                Position::fromTopLeft(6, 136),
                Position::fromTopLeft(32, 6),
                Position::fromTopLeft(32, 32),
                Position::fromTopLeft(32, 58),
                Position::fromTopLeft(32, 84),
                Position::fromTopLeft(32, 110),
                Position::fromTopLeft(32, 136),
                Position::fromTopLeft(32, 162),
                Position::fromTopLeft(58, 6),
                Position::fromTopLeft(58, 32),
                Position::fromTopLeft(58, 58),
                Position::fromTopLeft(58, 84),
                Position::fromTopLeft(58, 110),
                Position::fromTopLeft(58, 136),
                Position::fromTopLeft(58, 162),
                Position::fromTopLeft(84, 6),
                Position::fromTopLeft(84, 32),
                Position::fromTopLeft(84, 58),
                Position::fromTopLeft(84, 84),
                Position::fromTopLeft(84, 110),
                Position::fromTopLeft(84, 136),
                Position::fromTopLeft(84, 162),
                Position::fromTopLeft(110, 6),
                Position::fromTopLeft(110, 32),
                Position::fromTopLeft(110, 58),
                Position::fromTopLeft(110, 84),
                Position::fromTopLeft(110, 110),
                Position::fromTopLeft(110, 136),
                Position::fromTopLeft(110, 162),
                Position::fromTopLeft(136, 6),
                Position::fromTopLeft(136, 32),
                Position::fromTopLeft(136, 58),
                Position::fromTopLeft(136, 84),
                Position::fromTopLeft(136, 110),
                Position::fromTopLeft(136, 136),
                Position::fromTopLeft(136, 162),
                Position::fromTopLeft(162, 32),
                Position::fromTopLeft(162, 58),
                Position::fromTopLeft(162, 84),
                Position::fromTopLeft(162, 110),
                Position::fromTopLeft(162, 136),
                Position::fromTopLeft(162, 162),
            ],
        ];
        yield [
            Version::V39,
            [
                Position::fromTopLeft(6, 26),
                Position::fromTopLeft(6, 54),
                Position::fromTopLeft(6, 82),
                Position::fromTopLeft(6, 110),
                Position::fromTopLeft(6, 138),
                Position::fromTopLeft(26, 6),
                Position::fromTopLeft(26, 26),
                Position::fromTopLeft(26, 54),
                Position::fromTopLeft(26, 82),
                Position::fromTopLeft(26, 110),
                Position::fromTopLeft(26, 138),
                Position::fromTopLeft(26, 166),
                Position::fromTopLeft(54, 6),
                Position::fromTopLeft(54, 26),
                Position::fromTopLeft(54, 54),
                Position::fromTopLeft(54, 82),
                Position::fromTopLeft(54, 110),
                Position::fromTopLeft(54, 138),
                Position::fromTopLeft(54, 166),
                Position::fromTopLeft(82, 6),
                Position::fromTopLeft(82, 26),
                Position::fromTopLeft(82, 54),
                Position::fromTopLeft(82, 82),
                Position::fromTopLeft(82, 110),
                Position::fromTopLeft(82, 138),
                Position::fromTopLeft(82, 166),
                Position::fromTopLeft(110, 6),
                Position::fromTopLeft(110, 26),
                Position::fromTopLeft(110, 54),
                Position::fromTopLeft(110, 82),
                Position::fromTopLeft(110, 110),
                Position::fromTopLeft(110, 138),
                Position::fromTopLeft(110, 166),
                Position::fromTopLeft(138, 6),
                Position::fromTopLeft(138, 26),
                Position::fromTopLeft(138, 54),
                Position::fromTopLeft(138, 82),
                Position::fromTopLeft(138, 110),
                Position::fromTopLeft(138, 138),
                Position::fromTopLeft(138, 166),
                Position::fromTopLeft(166, 26),
                Position::fromTopLeft(166, 54),
                Position::fromTopLeft(166, 82),
                Position::fromTopLeft(166, 110),
                Position::fromTopLeft(166, 138),
                Position::fromTopLeft(166, 166),
            ],
        ];
        yield [
            Version::V40,
            [
                Position::fromTopLeft(6, 30),
                Position::fromTopLeft(6, 58),
                Position::fromTopLeft(6, 86),
                Position::fromTopLeft(6, 114),
                Position::fromTopLeft(6, 142),
                Position::fromTopLeft(30, 6),
                Position::fromTopLeft(30, 30),
                Position::fromTopLeft(30, 58),
                Position::fromTopLeft(30, 86),
                Position::fromTopLeft(30, 114),
                Position::fromTopLeft(30, 142),
                Position::fromTopLeft(30, 170),
                Position::fromTopLeft(58, 6),
                Position::fromTopLeft(58, 30),
                Position::fromTopLeft(58, 58),
                Position::fromTopLeft(58, 86),
                Position::fromTopLeft(58, 114),
                Position::fromTopLeft(58, 142),
                Position::fromTopLeft(58, 170),
                Position::fromTopLeft(86, 6),
                Position::fromTopLeft(86, 30),
                Position::fromTopLeft(86, 58),
                Position::fromTopLeft(86, 86),
                Position::fromTopLeft(86, 114),
                Position::fromTopLeft(86, 142),
                Position::fromTopLeft(86, 170),
                Position::fromTopLeft(114, 6),
                Position::fromTopLeft(114, 30),
                Position::fromTopLeft(114, 58),
                Position::fromTopLeft(114, 86),
                Position::fromTopLeft(114, 114),
                Position::fromTopLeft(114, 142),
                Position::fromTopLeft(114, 170),
                Position::fromTopLeft(142, 6),
                Position::fromTopLeft(142, 30),
                Position::fromTopLeft(142, 58),
                Position::fromTopLeft(142, 86),
                Position::fromTopLeft(142, 114),
                Position::fromTopLeft(142, 142),
                Position::fromTopLeft(142, 170),
                Position::fromTopLeft(170, 30),
                Position::fromTopLeft(170, 58),
                Position::fromTopLeft(170, 86),
                Position::fromTopLeft(170, 114),
                Position::fromTopLeft(170, 142),
                Position::fromTopLeft(170, 170),
            ],
        ];
    }
}
